# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[(b'cj', '\u521d\u7ea7'), (b'zj', '\u7ec8\u6781'), (b'gj', '\u9ad8\u7ea7')], max_length=2, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
